In [1]:
import numpy as np
import pandas as pd

In [2]:
# Series 생성(기본값이 None, data,index 순서, index=이라고 지정하지 않아도, 순서에 맞으면 인덱스로 들어감
population = pd.Series([9668465,3391946,2942828,1450062],
                      index=["서울","부산","인천","광주"])

In [3]:
population

서울    9668465
부산    3391946
인천    2942828
광주    1450062
dtype: int64

In [4]:
# 값 확인
print(population.values)
# 인덱스 확인
print(population.index)
# 타입 확인
print(population.dtype)

[9668465 3391946 2942828 1450062]
Index(['서울', '부산', '인천', '광주'], dtype='object')
int64

In [5]:
# 인덱싱
population[1],population["부산"]

C:\Users\User\AppData\Local\Temp\ipykernel_3248\2739830903.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  population[1],population["부산"]

(3391946, 3391946)

In [8]:
# 여러개의 행 인덱싱
print(population[[0,3,1]])

서울    9668465
광주    1450062
부산    3391946
dtype: int64

C:\Users\User\AppData\Local\Temp\ipykernel_3248\1481068761.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(population[[0,3,1]])

In [7]:
print(population[["서울","광주","부산"]])

서울    9668465
광주    1450062
부산    3391946
dtype: int64

In [9]:
data = {"피카츄":9631,"꼬부기":3393,"파이리":1490,"이상해씨":2632}
pokemon = pd.Series(data)
pokemon

피카츄     9631
꼬부기     3393
파이리     1490
이상해씨    2632
dtype: int64

In [10]:
data2 = {"피카츄":9904,"꼬부기":3448,"이브이":2466,"뮤":2890}
pokemon_up = pd.Series(data2)
pokemon_up

피카츄    9904
꼬부기    3448
이브이    2466
뮤      2890
dtype: int64

In [13]:
ex1 = [10,20,30]
s = pd.Series(ex1,index=["a","b","c"])
print(s)

a    10
b    20
c    30
dtype: int64

In [14]:
s2 = s.reindex(["d","e","f"])
print(s2)

d   NaN
e   NaN
f   NaN
dtype: float64

In [ ]:
#NaN : 값이 비어있거나 없다는 뜻
#notnull() , isnull()

In [15]:
data = {"2020":[9668465,3391946,2942828,1450062],
        "2010":[10312545,3567910,2758296,1454636]}
df = pd.DataFrame(data)
print(df)

      2020      2010
0  9668465  10312545
1  3391946   3567910
2  2942828   2758296
3  1450062   1454636

In [ ]:
# csv => comma separated values 쉼표를 기준으로 구분된 값
# encoding : 텍스트나 데이터를 컴퓨터에 저장하거나 전송하기 위한 형식으로 변경하는과정
# utf-8 범용적으로 사용
# cp-949 / euc-kr windows에 사용되는 한글 인코딩 방

In [ ]:
population = pd.read_csv("파일경로.csv",index_col = "도시")

In [ ]:
# sore_values() 기본값은 ascending=True, 오름차순

In [17]:
df["2020"].sort_values()
print(df)

      2020      2010
0  9668465  10312545
1  3391946   3567910
2  2942828   2758296
3  1450062   1454636

In [19]:
df["2010"].sort_values()

3     1454636
2     2758296
1     3567910
0    10312545
Name: 2010, dtype: int64

In [34]:
score = pd.DataFrame({
    '과목': ["파이썬", "db", "자바", "크롤링", "web"],
    '1반': [45, 76, 47, 92, 11],
    '2반': [44, 92, 92, 81, 79],
    '3반': [73, 45, 45, 85, 47],
    '4반': [39, 69, 69, 40, 26]
})

In [35]:
score.to_csv("score.csv",index=False,encoding="utf-8")

In [32]:
score = score.set_index("과목")

In [33]:
score

     1반  2반  3반  4반
과목
파이썬  45  44  73  39
db   76  92  45  69
자바   47  92  45  69
크롤링  92  81  85  40
web  11  79  47  26

In [ ]:
# apply() 함수 axis =0이 기본값
# axis =0 열을 기준, axis=1 행 기준으로 반복적으로 적용

In [22]:
def max_min(row):
    return row.max()-row.min()

In [23]:
result = score.loc[:"web",:"4반"].apply(max_min, axis=1)
print(result)

파이썬     7
db     10
자바      7
크롤링    12
web     5
dtype: int64

In [ ]:
# 데이터프레임 병합
# concat, merge

In [36]:
score.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   과목      5 non-null      object
 1   1반      5 non-null      int64
 2   2반      5 non-null      int64
 3   3반      5 non-null      int64
 4   4반      5 non-null      int64
dtypes: int64(4), object(1)
memory usage: 332.0+ bytes

In [37]:
score.describe()

            1반         2반         3반         4반
count   5.0000   5.000000   5.000000   5.000000
mean   54.2000  77.600000  59.000000  48.600000
std    31.2522  19.730687  18.761663  19.424212
min    11.0000  44.000000  45.000000  26.000000
25%    45.0000  79.000000  45.000000  39.000000
50%    47.0000  81.000000  47.000000  40.000000
75%    76.0000  92.000000  73.000000  69.000000
max    92.0000  92.000000  85.000000  69.000000

In [40]:
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})
df3 = pd.DataFrame({'A': [9, 10], 'B': [11, 12]})

# 세로로 결합
result = pd.concat([df1, df2, df3], axis=0)
print(result)

    A   B
0   1   3
1   2   4
0   5   7
1   6   8
0   9  11
1  10  12