In [1]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv("./data/score.csv",encoding="utf-8")
df

    과목  1반  2반  3반  4반
0  파이썬  45  44  73  39
1   db  76  92  45  69
2   자바  47  92  45  69
3  크롤링  92  81  85  40
4  web  11  79  47  26

In [8]:
df = df.set_index("과목")
df

     1반  2반  3반  4반
과목
파이썬  45  44  73  39
db   76  92  45  69
자바   47  92  45  69
크롤링  92  81  85  40
web  11  79  47  26

In [9]:
df["합계"] = df.sum(axis=1)
df

     1반  2반  3반  4반   합계
과목
파이썬  45  44  73  39  201
db   76  92  45  69  282
자바   47  92  45  69  253
크롤링  92  81  85  40  298
web  11  79  47  26  163

In [ ]:
df["평균"] = df.loc[:,:"4반"].mean(axis=1)
df

     1반  2반  3반  4반   합계     평균
과목
파이썬  45  44  73  39  201  50.25
db   76  92  45  69  282  70.50
자바   47  92  45  69  253  63.25
크롤링  92  81  85  40  298  74.50
web  11  79  47  26  163  40.75

In [11]:
df.loc["반평균"] = df.loc[:,:].mean()
df

       1반    2반    3반    4반     합계     평균
과목
파이썬  45.0  44.0  73.0  39.0  201.0  50.25
db   76.0  92.0  45.0  69.0  282.0  70.50
자바   47.0  92.0  45.0  69.0  253.0  63.25
크롤링  92.0  81.0  85.0  40.0  298.0  74.50
web  11.0  79.0  47.0  26.0  163.0  40.75
반평균  54.2  77.6  59.0  48.6  239.4  59.85

In [12]:
df.max()

1반     92.0
2반     92.0
3반     85.0
4반     69.0
합계    298.0
평균     74.5
dtype: float64

In [13]:
df.min()

1반     11.00
2반     44.00
3반     45.00
4반     26.00
합계    163.00
평균     40.75
dtype: float64

In [14]:
df.max(axis=1)

과목
파이썬    201.0
db     282.0
자바     253.0
크롤링    298.0
web    163.0
반평균    239.4
dtype: float64

In [15]:
df.min(axis=1)

과목
파이썬    39.0
db     45.0
자바     45.0
크롤링    40.0
web    11.0
반평균    48.6
dtype: float64

In [17]:
maxarr = df.loc[:"web",:"4반"].max(axis=1)
maxarr

과목
파이썬    73.0
db     92.0
자바     92.0
크롤링    92.0
web    79.0
dtype: float64

In [ ]:
# apply() 함수 axis =0이 기본값
# axis =0 열을 기준, axis=1 행 기준으로 반복적으로 적용

In [18]:
def max_min(row):
    return row.max()-row.min()

In [19]:
result = df.loc[:"web",:"4반"].apply(max_min, axis=1)
print(result)

과목
파이썬    34.0
db     47.0
자바     47.0
크롤링    52.0
web    68.0
dtype: float64

In [22]:
data_dic = {"A":[1,3,3,4,4],"B":[1,2,2,3,3],"C":[1,2,4,4,5]}
df2 = pd.DataFrame(data_dic)
df2

   A  B  C
0  1  1  1
1  3  2  2
2  3  2  4
3  4  3  4
4  4  3  5

In [34]:
df3 = df2.apply(pd.value_counts)
df3

C:\Users\User\AppData\Local\Temp\ipykernel_14144\3292164470.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  df3 = df2.apply(pd.value_counts)

     A    B    C
1  1.0  1.0  1.0
2  NaN  2.0  1.0
3  2.0  2.0  NaN
4  2.0  NaN  2.0
5  NaN  NaN  1.0

In [ ]:
# fillna 함수는 원본에 영향을 주지않음.
# 원본을 바꾸려면, inplace=True 사용
df3.fillna(0)

     A    B    C
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [38]:
df3

     A    B    C
1  1.0  1.0  1.0
2  NaN  2.0  1.0
3  2.0  2.0  NaN
4  2.0  NaN  2.0
5  NaN  NaN  1.0

In [39]:
ages = [0,2,10,21,23,37,31,61,20,41,32,100]
bins = [0,15,25,35,60,99]
labels = ["미성년자","청년","중년","장년","노년"]
cate = pd.cut(ages,bins,labels=labels)

In [ ]:
# cut 함수는 카테고리형 배열을 만들어 줄 뿐, 데이터프레임으로 생성해주진 않음
# 따라서, 데이터프레임화 시키려면 추가적인 작업이 필요
cate

[NaN, '미성년자', '미성년자', '청년', '청년', ..., '노년', '청년', '장년', '중년', NaN]
Length: 12
Categories (5, object): ['미성년자' < '청년' < '중년' < '장년' < '노년']

In [41]:
cate.categories

Index(['미성년자', '청년', '중년', '장년', '노년'], dtype='object')

In [42]:
agearr = pd.DataFrame(ages,columns=["ages"])
agearr

    ages
0      0
1      2
2     10
3     21
4     23
5     37
6     31
7     61
8     20
9     41
10    32
11   100

In [43]:
agearr["구분"] = cate

In [44]:
agearr

    ages    구분
0      0   NaN
1      2  미성년자
2     10  미성년자
3     21    청년
4     23    청년
5     37    장년
6     31    중년
7     61    노년
8     20    청년
9     41    장년
10    32    중년
11   100   NaN

In [49]:
df1 = pd.DataFrame({"A":["A0","A1","A2","A3"],
                    "B":["B0","B1","B2","B3"],
                    "C":["C0","C1","C2","C3"],
                    "D":["D0","D1","D2","D3"]},
                    index=[0,1,2,3])

df2 = pd.DataFrame({"A":["A4","A5","A6","A7"],
                    "B":["B4","B5","B6","B7"],
                    "C":["C4","C5","C6","C7"],
                    "D":["D4","D5","D6","D7"]},
                    index=[4,5,6,7])

df3 = pd.DataFrame({"A":["A8","A9","A10","A11"],
                    "B":["B8","B9","B10","B11"],
                    "C":["C8","C9","C10","C11"],
                    "D":["D8","D9","D10","D11"]},
                    index=[8,9,10,11])

In [50]:
result = pd.concat([df1,df2,df3])
result

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [ ]:
#keys 속성 부여시 다중 index
# 각 데이터에 대한 라벨을 붙여주는 역할
# 여러 데이터를 구분할때 유용함
result = pd.concat([df1,df2,df3],keys=["x","y","z"])
result

        A    B    C    D
x 0    A0   B0   C0   D0
  1    A1   B1   C1   D1
  2    A2   B2   C2   D2
  3    A3   B3   C3   D3
y 4    A4   B4   C4   D4
  5    A5   B5   C5   D5
  6    A6   B6   C6   D6
  7    A7   B7   C7   D7
z 8    A8   B8   C8   D8
  9    A9   B9   C9   D9
  10  A10  B10  C10  D10
  11  A11  B11  C11  D11

In [52]:
df4 = pd.DataFrame({"B":["B2","B3","B6","B7"],
                    "D":["D2","D3","D6","D7"],
                    "F":["F2","F3","F6","F7"]},
                    index=[2,3,6,7])

In [53]:
result = pd.concat([df1,df4],axis=1)
result

     A    B    C    D    B    D    F
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7